# fly.toml file generated for gringobot on 2023-02-16T13:26:50Z

app = "gringobot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  NODE_ENV="production"
  DATA_PATH="./data"
  HELP_COMMAND_ENABLED="false"
  # TODO: add PNG prod
  CHATS_WITH_FORCED_PORTUGUESE="-1001406908646"

[mounts]
  source="gringobot_data"
  destination="/app/data"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
